### PR TITLE
✨ FH-3825 Allow Mobile Apps to be created from the MCP UI

### PR DESCRIPTION
**Pull request by david-martin**
* Update the Mobile left nav to open a Mobile Overview to show Apps & Services
* Add 'Apps' & 'Security' as top nav placeholders
* Add 'Create Mobile App' button to Mobile Overview page beside the Mobile Apps listing
* Hook up the button to a new view for creating a Mobile App
  * The new view allows the App Type and App Name to be specified
  * The new view is made up of:
    * create-mobileapp.html view and controller
    * create-mobileapp.html directive

image

image

### CODE REVIEW

**Comment by aidenkeating** [comment]
👀

**Review by aidenkeating — APPROVED** [review]
LGTM, gave it a try from scratch and everything works 👍  One question, should those `android` and `ios` labels on the Mobile App cards be formatted e.g. `Android`, `iOS`

**Comment by david-martin** [comment]
@aidenkeating yeah, that would make sense. A 'good-first-bug' :)
I'll add it

**Comment by david-martin** [comment]
@aidenkeating I created https://github.com/feedhenry/mobile-control-panel/issues/9

**Pull request merged**
